import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Noto_Sans } from "next/font/google";

export const roboto = Roboto({
  // Export the font object
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const notoSans = Noto_Sans({
  // Export the font object
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
